language: node_js
sudo: false
node_js:
  - "6"
  - "node"
script:
  - "npm run lint"
  - "npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
env:
  - REACT=0.14
  - REACT=15.4
  - REACT=15.5
  - REACT=15.6
before_script: "sh install-relevant-react.sh"
